name: Maintenance
description: Maintenance task.
title: "[Maintenance]: "
labels: ["chore"]
projects: ["tjololo/3"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Types
      description: Type of maintenance task
      options:
        - "[Terraform](terraform.io)"
        - 2 [Golang](go.dev)
        - 3 [Demo](exmaple.io)
  - type: textarea
    id: description
    attributes:
      label: Description
      description: More description
