name: Maintenance
description: Maintenance task.
title: "[Maintenance]: "
labels: ["chore"]
projects: ["tjololo/3"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Link to documentation
      description: Type of maintenance task
      options:
        - "[Terraform](terraform.io)"
        - "[Golang](go.dev)"
        - "[Demo](exmaple.io)"
        - "Other see description"
  - type: textarea
    id: description
    attributes:
      label: Description
      description: More description
      render: markdown
