name: Deployment A

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - prod
      release:
        description: 'Release version'
        required: true
        default: '0.0.1'
        type: string

jobs:
    deploy-staging:
        runs-on: ubuntu-latest
        name: Deploy to Staging
        environment: staging
        if: ${{ github.event.inputs.environment == 'staging' }}
        steps:
          - name: Checkout code
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            with:
              fetch-depth: 0
              ref: refs/tags/test-v${{ github.event.inputs.release }}
          - name: Dummy deploy step
            run: echo "Deploying to staging environment..."
    deploy-production:
        runs-on: ubuntu-latest
        name: Deploy to Production
        environment: prod
        if: ${{ github.event.inputs.environment == 'prod' }}
        steps:
          - name: Checkout code
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            with:
              fetch-depth: 0
              ref: refs/tags/test-v${{ github.event.inputs.release }}
          - name: Dummy deploy step
            run: echo "Deploying to production environment..."