name: dummy test renovate

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: tjololo/hello-actions/actions/composite@39c6fcda20078d6031935ab52176328574f5f399 # composite-v0.0.1
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}