name: dummy test renovate

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: tjololo/hello-actions/actions/composite@a4dfe6c039ba65b4b60e8766bea84e0328c48a08 # composite-v0.0.1
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}