name: dummy test renovate

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      # renovate: datasource=github-tags depName=hello-actions/actions packageName=tjololo/hello-actions versioning=semver extractVersion=^action-composite-(?<version>.*)$
      uses: tjololo/hello-actions/actions/composite@a51358cc1258263a002437c3f5578d73c7080c2d #regex v0.0.1
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}