name: Promote release from issue comment

on:
  issues:
    types: [edited]
  release:
    types: 
      - created
  push:
    branches:
      - main
    paths:
      - releases/oci-releases.json
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  create-issue:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created' && startsWith(github.event.release.tag_name, 'oci-')
    steps:
      - name: Create issue
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const issueTitle = `OCI Release: ${context.payload.release.tag_name}`;
            const issueBody = `A new release has been published. Check it out [here](${context.payload.release.html_url})
            - Release Name: ${context.payload.release.name}
            - Release Tag: ${context.payload.release.tag_name}
            - Release URL: ${context.payload.release.html_url}
            
            To create a pull request with updated release config file, please check the boxes below:
            <!-- start-env-list -->
            - [ ] Deploy to Staging
            - [ ] Deploy to Production
            <!-- stop-env-list -->
            `;
            // Check if the issue already exists
            const { data: issues } = await github.rest.issues.listForRepo({
              ...context.repo,
              state: 'open',
              labels: 'release'
            });
            const issueExists = issues.some(issue => issue.title === issueTitle);
            if (issueExists) {
              console.log(`Issue already exists: ${issueTitle}`);
              return;
            }
            // Create a new issue
            const response = await github.rest.issues.create({
              ...context.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['release']
            });
            console.log(`Issue created: ${response.data.html_url}`);
  create-release-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'edited' && startsWith(github.event.issue.title, 'OCI Release:') && github.event.issue.draft == false && github.event.issue.state == 'open'
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Promote release
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        id: update-release
        with:
          script: |
            const issueTitle = context.payload.issue.title
            const versionRegex = /OCI Release: oci-(.*?)-v(\d+\.\d+\.\d+)/;
            const match = issueTitle.match(versionRegex);
            if (!match) {
              console.log('No version found in release tag:', issueTitle);
              return;
            }
            const releaseName = match[1];
            const releaseVersion = match[2];
            core.setOutput('release-name', releaseName);
            core.setOutput('release-version', releaseVersion);
            console.log('Release version:', releaseVersion);
            
            const currentState = context.payload.issue.body;
            // find the checkboxes in the issue body starting with <!-- start-env-list --> and ending with <!-- stop-env-list -->
            const startEnvList = currentState.indexOf('<!-- start-env-list -->');
            const stopEnvList = currentState.indexOf('<!-- stop-env-list -->');
            const envList = currentState.substring(startEnvList + 23, stopEnvList);
            const envListLines = envList.split('\n').map(line => line.trim());
            const lineRegex = /- \[([ x])\] Deploy to (.+)$/;
            const envListCheckboxes = envListLines.map(line => {
              const match = line.match(lineRegex);
              if (match) {
                const checked = match[1] === 'x';
                const env = match[2];
                return { env, checkbox: checked };
              }
              return null;
            }).filter(Boolean);
            // Update releases config file and create new Pull Request
            const releasesConfigFile = `releases/oci-releases.json`;
            const releasesConfig = require(`./${releasesConfigFile}`);
            // Update environments in releases config file
            envListCheckboxes.forEach(env => {
              if (env.checkbox) {
                const envName = env.env.toLowerCase();
                if (!releasesConfig[releaseName]) {
                  releasesConfig[releaseName] = {};
                }
                releasesConfig[releaseName][envName] = releaseVersion;
              }
            });

            // Write the updated config back to the file
            const fs = require('fs');
            fs.writeFileSync(releasesConfigFile, JSON.stringify(releasesConfig, null, 2));
            console.log('Updated releases config:', releasesConfig);
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          title: 'Update releases config for ${{ steps.update-release.outputs.release-name }} to ${{ steps.update-release.outputs.release-version }}'
          body: 'This pull request updates the releases config file with the new release version.'
          base: main
          commit-message: 'Update flux releases config for ${{ steps.update-release.outputs.release-name }} to ${{ steps.update-release.outputs.release-version }}'
          branch: update-releases-config-${{ steps.update-release.outputs.release-name }}-${{ steps.update-release.outputs.release-version }}
          delete-branch: true
          labels: 'release'
          sign-commits: true
  retag-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Promote release
        run: |
          echo "Promoting release..."
          # Add your promotion logic here