name: Test release

on:
  push:

permissions:
  contents: read

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create zip
        run: |
          rm -rf /tmp/release
          mkdir /tmp/release
          rsync . -rv --exclude-from=.releaseignore /tmp/release
          tree /tmp/release
          zip -r ${{ github.event.repository.name }}.zip /tmp/release
          sha512sum ${{ github.event.repository.name }}.zip > ${{ github.event.repository.name }}.sha512sums.txt