name: Test release

on:
  push:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: create zip
        run: |
          rm -rf /tmp/release
          mkdir /tmp/release
          rsync . -rv --exclude-from=.releaseignore /tmp/release
          zip -r ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip /tmp/release
          sha512sum ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip > ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.sha512sums.txt
          tree /tmp/release
