name: Promote release from issue comment

on:
  issues:
    types: [edited]

jobs:
  promote-release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'Release:')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Promote release
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const releaseTag = context.payload.issue.title.split(': ')[1];
            const releaseVersion = releaseTag.replace('test-v', '');
            console.log('Release version:', releaseVersion);
            
            const currentState = context.payload.issue.body;
            // find the checkboxes in the issue body starting with <!-- start-env-list --> and ending with <!-- stop-env-list -->
            const startEnvList = currentState.indexOf('<!-- start-env-list -->');
            const stopEnvList = currentState.indexOf('<!-- stop-env-list -->');
            const envList = currentState.substring(startEnvList + 23, stopEnvList);
            const envListLines = envList.split('\n').map(line => line.trim());
            const lineRegex = /- \[([ x])\] Deploy to (.+)$/;
            const envListCheckboxes = envListLines.map(line => {
              const match = line.match(lineRegex);
              if (match) {
                const checked = match[1] === 'x';
                const env = match[2];
                return { env, checkbox: checked };
              }
              return null;
            }).filter(Boolean);
            // Old checkboxes
            const oldState = context.payload.changes.body.from;
            const oldStartEnvList = oldState.indexOf('<!-- start-env-list -->');
            const oldStopEnvList = oldState.indexOf('<!-- stop-env-list -->');
            const oldEnvList = oldState.substring(oldStartEnvList + 23, oldStopEnvList);
            const oldEnvListLines = oldEnvList.split('\n').map(line => line.trim());
            const oldEnvListCheckboxes = oldEnvListLines.map(line => {
              const match = line.match(lineRegex);
              if (match) {
                const checked = match[1] === 'x';
                const env = match[2];
                return { env, checkbox: checked };
              }
              return null;
            }).filter(Boolean);
            console.log('Old env list checkboxes:', oldEnvListCheckboxes);
            console.log('New env list checkboxes:', envListCheckboxes);
            // List environments newly checked
            const newCheckedEnvs = envListCheckboxes.filter(env => env.checkbox === true);
            const oldCheckedEnvs = oldEnvListCheckboxes.filter(env => env.checkbox === true);
            const newlyCheckedEnvs = newCheckedEnvs.filter(env => !oldCheckedEnvs.some(oldEnv => oldEnv.env === env.env));
            if (newlyCheckedEnvs.length === 0) {
              console.log('No new environments checked.');
              return;
            }
            // Update releases config file and create new Pull Request
            const releasesConfigFile = 'releases.json';
            const releasesConfig = require(`./${releasesConfigFile}`);
            // find environment and set version to releaseVersion
            const envsToUpdate = newlyCheckedEnvs.map(env => env.env.toLowerCase());
            console.log('Environments to update:', envsToUpdate);
            console.log('Releases config before update:', releasesConfig);
            const oldReleasesConfig = { ...releasesConfig };
            envsToUpdate.forEach(env => {
              if (releasesConfig[env]) {
                releasesConfig[env] = releaseVersion;
              }
            });
            // Write the updated config back to the file
            const fs = require('fs');
            fs.writeFileSync(releasesConfigFile, JSON.stringify(releasesConfig, null, 2));
            console.log('Updated releases config:', releasesConfig);
            if (JSON.stringify(oldReleasesConfig) === JSON.stringify(releasesConfig)) {
              console.log('No changes made to releases config.');
              return;
            }
            // Create a new branch and commit the changes
            const branchName = `update-releases`;
            const { data: refData } = await github.rest.git.getRef({
              ...context.repo,
              ref: 'heads/main'
            });
            const sha = refData.object.sha;
            await github.rest.git.createRef({
              ...context.repo,
              ref: `refs/heads/${branchName}`,
              sha: sha
            });
            // Create a new commit
            const commitMessage = `Update releases config for ${releaseTag}`;
            const { data: commitData } = await github.rest.git.createCommit({
              ...context.repo,
              message: commitMessage,
              tree: sha,
              parents: [sha]
            });
            // Update the branch with the new commit
            await github.rest.git.updateRef({
              ...context.repo,
              ref: `heads/${branchName}`,
              sha: commitData.sha
            });
            // Create a new Pull Request
            const prTitle = `Update releases config for ${releaseTag}`;
            const prBody = `This PR updates the releases config for ${releaseTag}.\n\nEnvironments updated:\n- ${newlyCheckedEnvs.map(env => env.env).join('\n- ')}`;
            const { data: prData } = await github.rest.pulls.create({
              ...context.repo,
              title: prTitle,
              body: prBody,
              head: branchName,
              base: 'main'
            });
            console.log('Pull request created:', prData.html_url);
            // Add a comment to the issue with the PR link
            const commentBody = `A new Pull Request has been created to update the releases config for ${releaseTag}.\n\nPull Request: [${prData.title}](${prData.html_url})`;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.payload.issue.number,
              body: commentBody
            });
            console.log('Comment added to issue:', commentBody);