name: Promote release from issue comment

on:
  issues:
    types: [edited]

jobs:
  promote-release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'Release:')
    steps:
      - name: Promote release
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const releaseTag = context.payload.issue.title.split(': ')[1];
            const releaseVersion = releaseTag.replace('test-v', '');
            console.log('Release version:', releaseVersion);
            
            const currentState = context.payload.issue.body;
            // find the checkboxes in the issue body starting with <!-- start-env-list --> and ending with <!-- stop-env-list -->
            const startEnvList = currentState.indexOf('<!-- start-env-list -->');
            const stopEnvList = currentState.indexOf('<!-- stop-env-list -->');
            const envList = currentState.substring(startEnvList + 23, stopEnvList);
            const envListLines = envList.split('\n').map(line => line.trim());
            const lineRegex = /- \[([ x])\] Deploy to (.+)$/;
            const envListCheckboxes = envListLines.map(line => {
              const match = line.match(lineRegex);
              if (match) {
                const checked = match[1] === 'x';
                const env = match[2];
                return { env, checkbox: checked };
              }
              return null;
            }).filter(Boolean);
            // Old checkboxes
            const oldState = context.payload.changes.body.from;
            const oldStartEnvList = oldState.indexOf('<!-- start-env-list -->');
            const oldStopEnvList = oldState.indexOf('<!-- stop-env-list -->');
            const oldEnvList = oldState.substring(oldStartEnvList + 23, oldStopEnvList);
            const oldEnvListLines = oldEnvList.split('\n').map(line => line.trim());
            const oldEnvListCheckboxes = oldEnvListLines.map(line => {
              const match = line.match(lineRegex);
              if (match) {
                const checked = match[1] === 'x';
                const env = match[2];
                return { env, checkbox: checked };
              }
              return null;
            }).filter(Boolean);
            console.log('Old env list checkboxes:', oldEnvListCheckboxes);
            console.log('New env list checkboxes:', envListCheckboxes);
            // List environments newly checked
            const newCheckedEnvs = envListCheckboxes.filter(env => env.checkbox === true);
            const oldCheckedEnvs = oldEnvListCheckboxes.filter(env => env.checkbox === true);
            const newlyCheckedEnvs = newCheckedEnvs.filter(env => !oldCheckedEnvs.some(oldEnv => oldEnv.env === env.env));
            console.log('Newly checked environments:', newlyCheckedEnvs);
        