name: Test release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create zip
        run: zip -r ${{ github.event.repository.name }}.zip ./TestData
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.event.repository.name }}.zip