name: Test Infra deploy

on:
  push:
    tags:
      - v*.*.*

env:
  working_dir: .github/scripts

permissions:
  id-token: write
  contents: read

jobs:
  purge:
    name: Purge azure front door cache
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        working-directory: ${{ env.working_dir }}
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Log in to Azure using OIDC
        uses: azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_OIDC_PURGE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_OIDC_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_OIDC_SUBSCRIPTION_ID }}
      - name: Purge cache
        uses: azure/CLI@v2.1.0
        env:
          FD_SUBSCRIPTION: ${{ secrets.AZURE_OIDC_SUBSCRIPTION_ID }}
          FD_RESOURCEGROUP: ${{ secrets.FG_RG }}
          FD_PROFILE: ${{ secrets.FD_PROFILE }}
          FD_ENDPOINT: ${{ secrets.FD_ENDPOINT }}
          FD_DOMAIN: ${{ secrets.FD_DOMAIN }}
        with:
          azcliversion: 2.30.0
          inlineScript: |
            ./.github/scripts/prune-cache.sh --path "/testblob/demo.json" --path "/testblob/unstable.json"