on:
 push:
  branches:
   - main

jobs:
  test:
    if: startsWith(github.ref, format('refs/heads/{0}', 'ma'))
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Hello World"
