name: Tag

on:
  push:
    tags:
      - "*-demo"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Get version from tags
        id: getv
        shell: bash
        run: |
          tag=${GITHUB_REF/refs\/tags\//}
          echo "version=${tag%-demo}" >> $GITHUB_OUTPUT
      - name: Print version
        shell: bash
        run: |
          echo "${{ steps.getv.outputs.version }}"