name: Tag

on:
  push:
    tags:
      - "*-demo"

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get version from tags
        id: version
        shell: bash
        run: |
          tag=${GITHUB_REF/refs\/tags\//}
          echo "${tag}"
          version=${tag%-demo}
          echo "test=${version}"
          echo "test=$version" >> $GITHUB_OUTPUT
          echo "tag=$tag" >> $GITHUB_OUTPUT
      - name: Print version
        run: |
          echo ${{ steps.version.output.test }}