name: Test Infra deploy

on:
  push:
    tags:
      - v*.*.*

env:
  working_dir: scripts

permissions:
  id-token: write
  contents: read

jobs:
  purge:
    name: Purge azure front door cache
    runs-on: ubuntu-latest
    environment: test
    defaults:
      run:
        working-directory: ${{ env.working_dir }}
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_OIDC_PURGE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_OIDC_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_OIDC_SUBSCRIPTION_ID }}
      - name: Purge cache
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az account list -o none