name: Output test

on:
  workflow_dispatch:


jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Get version from tags
        id: out
        shell: bash
        run: |
          var=${GITHUB_REF/refs\//}
          echo "var=${var}" >> $GITHUB_OUTPUT
          echo "test=test" >> $GITHUB_OUTPUT
      - name: Print version
        shell: bash
        run: |
          echo ${{ steps.out.outputs.var }}
          echo ${{ steps.out.outputs.test }}