name: Test Composite

on:
  workflow_dispatch:


jobs:
  comp:
    name: Composite
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Hello"
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Test a composite
        uses: tjololo/hello-actions/actions/test@main
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}