name: Tag

on:
  push:
    tags:
      - "*-demo"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get version from tags
        id: getv
        shell: bash
        run: |
          tag=${GITHUB_REF/refs\/tags\//}
          echo "${tag}"
          version=${tag%-demo}
          echo "test=${version}"
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "TAG=$tag" >> $GITHUB_OUTPUT
          echo "test=test" >> $GITHUB_OUTPUT
      - name: Print version
        shell: bash
        run: |
          echo "${{ steps.getv.output.version }}"
          echo ${{ steps.getv.output.TAG }}
          echo ${{ steps.getv.output.test }}